CC=gcc
CFLAGS=-Wall -Wextra -Wpedantic -std=c17 -O3 -march=native -g -fopenmp
LDFLAGS=-lpthread

TARGETS=mc_pi_pthreads mc_pi_atomic mc_pi_critical mc_pi_reduction

.PHONY: all clean

all: $(TARGETS)

clean:
	$(RM) $(TARGETS)

%: %.c
	$(CC) $(CFLAGS) $< -o $@ $(LDFLAGS)
